# exercise to run: 1 / 2 / 3
exercise: 3

# data folder
data_folder: data

# ex1
gate: 'and' # and / xor

# ex2
ex2_training: ex2_traindata.txt
ex2_output: desired_output.txt
perceptron_type: 'linear' # linear / non_linear_tanh / non_linear_sigmoid

# ex3
ex3_training: ex3_traindata.txt
subitem: 3  # 1 / 2 / 3



