# exercise to run: 1 / 2 / 3
exercise: 3

# data folder
data_folder: data

# ex2
ex2_training: ex2_traindata.txt
ex2_output: desired_output.txt

# ex3
ex3_training: ex3_traindata.txt
subitem: 2  # 1 / 2 / 3 / 4



