#population size
N: 25

# people to select
K: 10

# warrior / archer / tank / rogue
class: warrior

# selection method: roulette / universal / elite / ranking / boltzmann / det_tourney / prob_tourney
selection_method: elite

# crossover: uniform / point / two_point / anular
crossover: uniform

# mutation: gen / limited_multigen / uniform_multigen / complete_mutation
mutation: complete_multigen
probability: 100

# implementation: fill_all / fill_parent
implementation: fill_all

# end by: time / max_gen / fitness / structure / content
end_by: time
params:
  time: 5
  gen_number: 5
  fitness: 40
  content_gen: 10





