#population size
N: 25

# people to select
K: 10

# warrior / archer / tank / rogue
class: warrior

# selection method: roulette / universal / elite / ranking / boltzmann / det_tourney / prob_tourney
selection_method: roulette

# crossover: uniform / point / two_point / anular
crossover: uniform

# mutation: gen / limited_multigen / uniform_multigen / complete_mutation
mutation: gen
probability: 10

# implementation: fill_all / fill_parent
implementation: fill_all

# end by: time / max_gem / fitness / structure / content
end_by: max_gen
params:
  time: 5
  gen_number: 5
  fitness: 10





